name: 💥 Request a new Feature
title: 💥 Add a new feature.
description: Have an idea that would make life easier for others? You can request a new feature here.
labels: [enhancement,under review]
body:
  - type: dropdown
    id: version
    attributes:
      label: 🔢 Version
      description: Which version of Mauve are you currently using?
      options:
        - 🐣 Pre-Release
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: 🌠 Product
      description: Which sub-product of Mauve is this feature for?
      options:
        - Ⓜ️ Framework
        - 📝 Dapper Support Kit
        - 💻 RestSharp Support Kit
        - 🦄 Visual Studio Community Extension
        - 🐲 Visual Studio Code Extension
    validations:
      required: true
  - type: textarea
    attributes:
      label: 😭 What problem does your proposition aim to solve?
      description: If your feature request is related to a problem, describe it clearly.
      placeholder: When I'm using a `foreach` loop, I can't get the next or previous element in my collection without having a separate variable or overly verbose code.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📝 How would you like the feature to work?
      description: Please give a brief explanation and a sample implementation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🎲 What have you already tried?
      description: Describe alternatives you've considered.