name: 🧪 Request a new Test Case
title: 🧪 Add a new test case.
description: Have an idea for a test case we haven't accounted for yet? Share it with us, it'll only make Mauve stronger.
labels: [test,under review]
body:
  - type: dropdown
    id: version
    attributes:
      label: 🔢 Version
      description: Which version of Mauve are you currently using?
      options:
        - 🐣 Pre-Release
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: 🌠 Product
      description: Which sub-product of Mauve is this test for?
      options:
        - Ⓜ️ Framework
        - 📝 Dapper Support Kit
        - 💻 RestSharp Support Kit
    validations:
      required: true
  - type: input
    attributes:
      label: 🦖 What type is this test for?
      description: Please include the namespace and type if applicable.
  - type: textarea
    attributes:
      label: 😭 What problem does your proposition aim to solve?
      description: Please give a brief explanation and a sample implementation.
  - type: textarea
    attributes:
      label: 📝 How would you like the test case to work?
      description: Please give a brief explanation and a sample implementation.